apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-costs-web
  namespace: spark-costs-test
  labels:
    app: spark-costs-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-costs-web
  template:
    metadata:
      labels:
        app: spark-costs-web
    spec:
      containers:
      - name: spark-costs-web
        image: oopjot/spark-costs:latest
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0"]
        envFrom:
        - configMapRef:
            name: spark-costs
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: spark-costs.spark-costs-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spark-costs.spark-costs-db.credentials.postgresql.acid.zalan.do
              key: password
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 256Mi
        ports:
        - containerPort: 8000
          name: web

---
apiVersion: v1
kind: Service
metadata:
  name: spark-costs-web
  labels:
    app: spark-costs-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: web
      protocol: TCP
      name: http
  selector:
    app: spark-costs-web

