services:
  api:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/opt/app
    environment:
      DB_HOST: database
      DB_USER: lolek
      DB_PASSWORD: tajne
      DB_NAME: surveys
      DB_PORT: 5432
      SECRET_API_KEY: SECRET_API_KEY
    depends_on:
      - database

  worker:
    build:
      context: .
    command: celery -A worker.celery worker --loglevel=INFO
    restart: always
    volumes:
      - .:/opt/app
    environment:
      DB_HOST: database
      DB_USER: lolek
      DB_PASSWORD: tajne
      DB_NAME: surveys
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - redis
      - database

  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lolek
      POSTGRES_PASSWORD: tajne
      POSTGRES_DB: surveys

  redis:
    image: redis
