name: Release Monitor
on:
  push:
    branches:
    - main
    paths:
    - ./mon
  workflow_dispatch: {}

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world"
