name: Release API and Worker
on:
  push:
    branches:
    - main
    paths:
    - ./api
  workflow_dispatch: {}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: oopjot
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t spark-costs -f ./api/Dockerfile ./api

      - name: Tag images
        run: docker tag spark-costs oopjot/spark-costs:$GITHUB_SHA && docker tag spark-costs oopjot/spark-costs:latest

      - name: Push Docker image to DockerHub
        run: docker push oopjot/spark-costs:$GITHUB_SHA oopjot/spark-costs:latest

